# Generated by Django 4.2.11 on 2024-04-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modelo_carro_preferido',
            field=models.CharField(choices=[('caminhonete', 'Caminhonete'), ('suv', 'SUV'), ('sedan', 'Sedan'), ('hatch', 'Hatch')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(default=86999999999, max_length=15),
            preserve_default=False,
        ),
    ]
