# Generated by Django 4.2.11 on 2024-04-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='cargo',
            new_name='Dupla',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='colega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.funcionario'),
        ),
    ]
