# Generated by Django 4.2.11 on 2024-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_cargo_funcionario_dupla_funcionario_colega'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filial_preferida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
