# Generated by Django 4.2.11 on 2024-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_userprofile_filial_preferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lavagem', models.CharField(max_length=100)),
            ],
        ),
    ]
