# Generated by Django 4.2.11 on 2024-04-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_tipolavagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoLavagem',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_lavagem',
            field=models.CharField(choices=[('LAVAGEM_TECNICA', 'LAVAGEM TÉCNICA'), ('LIMPEZA_DETALHADA', 'LIMPEZA DETALHADA'), ('LIMPEZA_COMPLETA', 'LIMPEZA COMPLETA')], default='', max_length=100),
        ),
    ]
