# Generated by Django 4.2.11 on 2024-04-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_userprofile_dia_alter_userprofile_tipo_lavagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dia',
            new_name='dia_semana',
        ),
    ]
