# Generated by Django 4.2.11 on 2024-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_rename_dia_userprofile_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='horario',
            field=models.CharField(choices=[('08:00', '08:00M'), ('09:00', '09:00M'), ('10:00', '10:00M'), ('11:00', '11:00M'), ('12:00', '12:00M'), ('13:00', '13:00T'), ('14:00', '14:00T'), ('15:00', '15:00T'), ('16:00', '16:00T')], default='', max_length=20),
        ),
    ]
