# Generated by Django 4.2.11 on 2024-04-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_userprofile_options_alter_userprofile_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Relatórios de Agendamento'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='veículo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modelo_carro_preferido',
            field=models.CharField(choices=[('PICAPE', 'PICAPE'), ('SUV', 'SUV'), ('SEDAN', 'SEDAN'), ('HATCH', 'HATCH'), ('MOTO', 'MOTO'), ('MOTO2', 'MOTO ESPORTIVA')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_lavagem',
            field=models.CharField(choices=[('LAVAGEM_TECNICA', 'LAVAGEM TÉCNICA'), ('LAVAGEM_TECNICA_M', 'LAVAGEM TÉCNICA MOTO'), ('LIMPEZA_DETALHADA', 'LIMPEZA DETALHADA'), ('LIMPEZA_DETALHADA_PROTECAO', 'LIMPEZA DETALHADA + PROTEÇÃO'), ('POLIMENTO_TECNICO_PROTECAO_6_M', 'POLIMENTO TECNICO + PROTEÇÃO DE 6 MESES'), ('POLIMENTO_TECNICO_M', 'POLIMENTO TECNICO MOTO'), ('LIMPEZA_CHASSI_DETALHADA', 'LIMPEZA CHASSI DETALHADA'), ('HIGIENIZAÇÃO_DE_BANCOS_COURO', 'HIGIENIZAÇÃO DE BANCOS COURO'), ('LIMPEZA_DE_MOTOR_COM_ENVENIZAMENTO', 'LIMPEZA DE MOTOR COM ENVENIZAMENTO'), ('DESCONTAMINAÇÃO', 'DESCONTAMINAÇÃO'), ('CERA_EM_PASTA', 'CERA EM PASTA'), ('REMOÇÃO_DE_CHUVA_ACIDA_E_VITRIFICAÇÃO_DO_PARABRIZA', 'REMOÇÃO DE CHUVA ACIDA E VITRIFICAÇÃO DO PARABRIZA'), ('POLIMENTO_TECNICO_VITRIFICAÇÃO', 'POLIMENTO TECNICO + VITRIFICAÇÃO DE PINTURA ( 1 ANO PROTEÇÃO )'), ('PACOTE_COMPLETO_VITRIFICAÇÃO', 'PACOTE COMPLETO VITRIFICAÇÃO COMPLETA'), ('VITRIFICAÇÃO_M', 'VITRIFICAÇÃO MOTO'), ('HIGIENIZAÇÃO_DE_BANCOS_TÉCNICO_5L', 'HIGIENIZAÇÃO DE BANCOS TÉCNICO'), ('HIGIENIZAÇÃO_DE_BANCOS_TÉCNICO_7L', 'HIGIENIZAÇÃO DE BANCOS TÉCNICO')], default='', max_length=100),
        ),
    ]
