# Generated by Django 4.2.11 on 2024-04-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_userprofile_options_userprofile_veículo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='veículo',
            new_name='veiculo',
        ),
    ]
