# Generated by Django 4.2.11 on 2024-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_rename_veículo_userprofile_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_atual',
            field=models.DateField(blank=True, null=True),
        ),
    ]
