# Generated by Django 4.2.11 on 2024-05-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_userprofile_data_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='', max_length=20),
        ),
    ]
