# Generated by Django 4.2.11 on 2024-05-01 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_alter_userprofile_data_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
