# Generated by Django 4.2.11 on 2024-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_agendamento_data_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='semana',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='', max_length=20),
        ),
    ]
