# Generated by Django 4.2.11 on 2024-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dia_semana',
            field=models.DateField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='horario',
            field=models.DateField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='', max_length=20),
        ),
    ]
