# Generated by Django 4.2.11 on 2024-05-01 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_alter_userprofile_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
