# Generated by Django 4.2.11 on 2024-05-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_agendamento_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
