# Generated by Django 4.2.11 on 2024-05-02 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_alter_agendamento_dia_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_agendamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='dia_semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dia_semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='', max_length=20),
        ),
    ]
