# Generated by Django 4.2.11 on 2024-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_alter_userprofile_data_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data_agendamento',
        ),
    ]
