# Generated by Django 4.2.11 on 2024-05-08 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_rename_horario_semana_horario2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semana',
            old_name='horario2',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='horario1',
            new_name='horario',
        ),
    ]
