# Generated by Django 4.2.11 on 2024-06-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_rename_colega_funcionario_parceiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField()),
                ('horario', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], max_length=20)),
                ('tipo_lavagem', models.CharField(choices=[('LAVAGEM_TECNICA', 'LAVAGEM TÉCNICA'), ('LAVAGEM_TECNICA_M', 'LAVAGEM TÉCNICA MOTO'), ('LIMPEZA_DETALHADA', 'LIMPEZA DETALHADA'), ('LIMPEZA_DETALHADA_PROTECAO', 'LIMPEZA DETALHADA + PROTEÇÃO'), ('POLIMENTO_TECNICO_PROTECAO_6_M', 'POLIMENTO TECNICO + PROTEÇÃO DE 6 MESES'), ('POLIMENTO_TECNICO_M', 'POLIMENTO TECNICO MOTO'), ('LIMPEZA_CHASSI_DETALHADA', 'LIMPEZA CHASSI DETALHADA'), ('HIGIENIZAÇÃO_DE_BANCOS_COURO', 'HIGIENIZAÇÃO DE BANCOS COURO'), ('LIMPEZA_DE_MOTOR_COM_ENVENIZAMENTO', 'LIMPEZA DE MOTOR COM ENVENIZAMENTO'), ('DESCONTAMINAÇÃO', 'DESCONTAMINAÇÃO'), ('CERA_EM_PASTA', 'CERA EM PASTA'), ('REMOÇÃO_DE_CHUVA_ACIDA_E_VITRIFICAÇÃO_DO_PARABRIZA', 'REMOÇÃO DE CHUVA ACIDA E VITRIFICAÇÃO DO PARABRIZA'), ('POLIMENTO_TECNICO_VITRIFICAÇÃO', 'POLIMENTO TECNICO + VITRIFICAÇÃO DE PINTURA ( 1 ANO PROTEÇÃO )'), ('PACOTE_COMPLETO_VITRIFICAÇÃO', 'PACOTE COMPLETO VITRIFICAÇÃO COMPLETA'), ('VITRIFICAÇÃO_M', 'VITRIFICAÇÃO MOTO'), ('HIGIENIZAÇÃO_DE_BANCOS_TÉCNICO_5L', 'HIGIENIZAÇÃO DE BANCOS TÉCNICO'), ('HIGIENIZAÇÃO_DE_BANCOS_TÉCNICO_7L', 'HIGIENIZAÇÃO DE BANCOS TÉCNICO')], default='', max_length=100)),
                ('lavagem_adicional', models.CharField(choices=[('LAVAGEM_TECNICA', 'LAVAGEM TÉCNICA'), ('LAVAGEM_TECNICA_M', 'LAVAGEM TÉCNICA MOTO'), ('LIMPEZA_DETALHADA', 'LIMPEZA DETALHADA'), ('LIMPEZA_DETALHADA_PROTECAO', 'LIMPEZA DETALHADA + PROTEÇÃO'), ('POLIMENTO_TECNICO_PROTECAO_6_M', 'POLIMENTO TECNICO + PROTEÇÃO DE 6 MESES'), ('POLIMENTO_TECNICO_M', 'POLIMENTO TECNICO MOTO'), ('LIMPEZA_CHASSI_DETALHADA', 'LIMPEZA CHASSI DETALHADA'), ('HIGIENIZAÇÃO_DE_BANCOS_COURO', 'HIGIENIZAÇÃO DE BANCOS COURO'), ('LIMPEZA_DE_MOTOR_COM_ENVENIZAMENTO', 'LIMPEZA DE MOTOR COM ENVENIZAMENTO'), ('DESCONTAMINAÇÃO', 'DESCONTAMINAÇÃO'), ('CERA_EM_PASTA', 'CERA EM PASTA'), ('REMOÇÃO_DE_CHUVA_ACIDA_E_VITRIFICAÇÃO_DO_PARABRIZA', 'REMOÇÃO DE CHUVA ACIDA E VITRIFICAÇÃO DO PARABRIZA'), ('POLIMENTO_TECNICO_VITRIFICAÇÃO', 'POLIMENTO TECNICO + VITRIFICAÇÃO DE PINTURA ( 1 ANO PROTEÇÃO )'), ('PACOTE_COMPLETO_VITRIFICAÇÃO', 'PACOTE COMPLETO VITRIFICAÇÃO COMPLETA'), ('VITRIFICAÇÃO_M', 'VITRIFICAÇÃO MOTO'), ('HIGIENIZAÇÃO_DE_BANCOS_TÉCNICO_5L', 'HIGIENIZAÇÃO DE BANCOS TÉCNICO'), ('HIGIENIZAÇÃO_DE_BANCOS_TÉCNICO_7L', 'HIGIENIZAÇÃO DE BANCOS TÉCNICO')], default='', max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
        ),
    ]
