# Generated by Django 4.2.11 on 2024-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dupla_registrada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
