# Generated by Django 4.2.11 on 2024-06-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_agendamento_dupla_registrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='lavagem_adicional',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='tipo_lavagem',
        ),
    ]
