# Generated by Django 4.2.11 on 2024-06-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_agendamento_lavagem_adicional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
