# Generated by Django 4.2.11 on 2024-06-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0045_dupla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='dupla_registrada',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='dupla_registrada',
            field=models.ManyToManyField(to='usuarios.dupla'),
        ),
    ]
