# Generated by Django 4.2.11 on 2024-06-17 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0054_alter_funcionario_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplas', to='usuarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='chave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dupla'),
        ),
    ]
